language: java

env:
  global:
    - MAVEN_OPTS="-Xmx256M"
    - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"
  matrix:
    - TEST_MODULES=!presto-tests,!presto-kafka,!presto-redis,!presto-cassandra,!presto-raptor,!presto-postgresql,!presto-mysql
    - TEST_MODULES=presto-tests
    - TEST_MODULES=presto-raptor,presto-redis,presto-cassandra,presto-kafka,presto-postgresql,presto-mysql
    - PRODUCT_TESTS=true
    - INTEGRATION_TESTS=true

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer

services:
  - docker

before_install:
  # This section can be removed once travis get equipped with docker 1.10 and docker-compose 1.6
  - |
    if [ -v PRODUCT_TESTS ] || [ -v INTEGRATION_TESTS ]; then
      sudo apt-get update
      sudo apt-get -o "Dpkg::Options::=--force-confold" -y install docker-engine
      sudo rm /usr/local/bin/docker-compose
      curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > docker-compose
      chmod +x docker-compose
      sudo mv docker-compose /usr/local/bin
    fi

install: ./mvnw install -DskipTests=true $MAVEN_SKIP_CHECKS_AND_DOCS -B -q -T C1 -pl '!presto-docs,!presto-server-rpm'

script:
  - |
    test ! -v TEST_MODULES ||
      ./mvnw test $MAVEN_SKIP_CHECKS_AND_DOCS -B -pl $TEST_MODULES
  - |
    test ! -v PRODUCT_TESTS ||
      presto-product-tests/bin/run_on_docker.sh \
        singlenode -x quarantine,big_query,storage_formats,mysql_connector,postgresql_connector,profile_specific_tests
  - |
    test ! -v PRODUCT_TESTS ||
      presto-product-tests/bin/run_on_docker.sh \
        singlenode-kerberos-hdfs-impersonation -g storage_formats,cli,hdfs_impersonation,authorization
  - |
    test ! -v INTEGRATION_TESTS ||
      presto-hive-hadoop2/bin/run_on_docker.sh
  - |
    test ! -v INTEGRATION_TESTS ||
      ./mvnw install -DskipTests=true -B

notifications:
  slack:
    secure: V5eyoGShxFoCcYJcp858vf/T6gC9KeMxL0C1EElcpZRcKBrIVZzvhek3HLHxZOxlghqnvNVsyDtU3u5orkEaAXeXj5c2dN+4XBsAB9oeN5MtQ0Z3VLAhZDqKIW1LzcXrq4DpzM0PkGhjfjum/P94/qFYk0UckPtB6a341AuYRo8=
